### ISSUE TITLE
Expose background and text color to MessageBar

### ISSUE THREAD

**Issue by jqn** [Qlean/react-native-messages#10]
Hi thanks for this component. I was thinking it would be nice to be able to change the default component's background color and text color without the need of creating a custom component.

**Comment by atiupin** [comment]
@jqn thank you for your feedback.

I suggest you to create custom component anyway. Default message component is meant to be used for demo purposes only. There is no way to consider every customisation case, so we've decided not to bloat API and give users a way to replace component completely.

**Comment by jqn** [comment]
That's fine. My thinking is that would make this component usable out of the box since all I needed was to change the background and the text color. It also wasn't immediately clear how to use the customComponent prop. I don't think you have to think about every customization case is more about thinking about usability.

**Comment by atiupin** [comment]
Sorry for that. I'll try to convey it more clearly in readme.
