### ISSUE TITLE
Error Cannot read property 'pushMessage' of null

### ISSUE THREAD

**Issue by 4external** [Qlean/react-native-messages#2]
Hi!

Have error 
```
YellowBox.js:82 Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'pushMessage' of null
TypeError: Cannot read property 'pushMessage' of null
```

I have component which is 'master-layout' - header, scrollview, navbar, etc. In this component i add _MessageBar_. Let's call it layout-component.

I make App with rn-navigation with StackNavigator.
On first screen i use layout-component, messages correctly appear when press-button.
Than on second screen i also use layout-component. Than back on first screen and press again button which call _showMessage_  we get error above.

Message component in MessageBar is default.

**Comment by atiupin** [comment]
@4external you should mount MessageBar above navigator, like this:

```
<View>
  <RootNavigator navigation={...}/>
  <MessageBar/>
</View>
```

`react-native-messages` relies on single mounted instance to work correctly.

**Comment by 4external** [comment]
Thank you.
Sorry, did not see a  5 days ago closed similar question.
