### ISSUE TITLE
Display over Modal component

### ISSUE THREAD

**Issue by Xyzor** [Qlean/react-native-messages#9]
Hello!

First, I'd like to thank you for this awesome package.

I'm curious if it's possible to display the message component over the *built in modal's grey overlay component?

Thanks.

*https://facebook.github.io/react-native/docs/modal.html

**Comment by atiupin** [comment]
@Xyzor I've investigated a bit on issue and I don't think it's possible without initialising `MessageBar` inside modal, which is a weird and buggy way. Probably same thing applies to all other native navigation components.

I suggest you to use `react-navigation` and custom JS-written modals with native driver animations. It's easy enough to implement and native modals interacts with `react-navigation` weirdly anyway.
